#!/bin/bash
set -e

NETWORK="testnet"
DEPLOYER="deployer"
WASM="target/wasm32-unknown-unknown/release/trustlend.wasm"

echo ""
echo "=================================================="
echo "  TrustLend — Soroban Deploy Script"
echo "  Network : $NETWORK"
echo "=================================================="
echo ""

# ── 1. Build ──────────────────────────────────────────────────────────────
echo "==> Building TrustLend contract..."
stellar contract build
echo "[OK] Build complete: $WASM"
echo ""

# ── 2. Ensure deployer key exists ─────────────────────────────────────────
if ! stellar keys ls 2>/dev/null | grep -q "^${DEPLOYER}$"; then
    echo "==> Generating deployer keypair and funding on $NETWORK..."
    stellar keys generate "$DEPLOYER" --network "$NETWORK" --fund
    echo "[OK] Deployer key created and funded"
else
    echo "==> Using existing deployer key: $DEPLOYER"
fi
echo ""

# ── 3. Deploy TrustLend contract ──────────────────────────────────────────
echo "==> Deploying TrustLend contract to $NETWORK..."
TRUSTLEND_CONTRACT_ID=$(stellar contract deploy \
    --wasm "$WASM" \
    --source "$DEPLOYER" \
    --network "$NETWORK")

echo "[OK] TrustLend deployed"
echo ""

# ── 4. Initialize TrustLend contract ────────────────────────────────────────
echo "==> Initializing TrustLend contract..."
DEPLOYER_PUBKEY=$(stellar keys address "$DEPLOYER")
NATIVE_XLM="CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC"

stellar contract invoke \
    --id "$TRUSTLEND_CONTRACT_ID" \
    --source "$DEPLOYER" \
    --network "$NETWORK" \
    -- \
    initialize \
    --admin "$DEPLOYER_PUBKEY" \
    --token "$NATIVE_XLM"

echo "[OK] TrustLend initialized with Testnet XLM"
echo ""

# ── 5. Summary ────────────────────────────────────────────────────────────
echo "=================================================="
echo "  Deployment Complete"
echo "=================================================="
echo "  TRUSTLEND_CONTRACT_ID=$TRUSTLEND_CONTRACT_ID"
echo "=================================================="
echo ""
echo "Paste the above into your backend/.env and frontend/.env"
echo ""

# ── 5. Optionally write to .env.deploy (never committed) ──────────────────
cat > .env.deploy <<EOF
# Auto-generated by scripts/deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
TRUSTLEND_CONTRACT_ID=$TRUSTLEND_CONTRACT_ID
EOF
echo "[OK] Contract IDs saved to .env.deploy (gitignored)"
